set_property SRC_FILE_INFO {cfile:C:/Users/vegar/Desktop/LogoCar/Jose_CPU_RAM_Expanded/MIDI_PLAYER_DANKNESS/MIDI_PLAYER_DANKNESS.srcs/constrs_1/new/speaker.xdc rfile:../../../MIDI_PLAYER_DANKNESS.srcs/constrs_1/new/speaker.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports reset]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports snd]
